os:
  - linux
language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.0
    - android-28
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

# branches:
#   only:
#   - master
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid

before_install:
  - yes | sdkmanager "platforms;android-28"
before_script:
  - git clone https://github.com/flutter/flutter.git ../flutter
  - ../flutter/bin/flutter doctor
  - chmod +x scripts/deploy_telegram.sh
script:
  - ../flutter/bin/flutter test
after_script:
 - python3 scripts/format_files.py
cache:
  directories:
    - $HOME/.pub-cache

deploy:
  - provider: script
    skip_cleanup: true
    script: scripts/deploy_telegram.sh
    on:
      branch: master
