os:
  - linux

language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.0
    - android-28
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

# branches:
#   only:
#   - master
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid

before_install:
  - yes | sdkmanager "platforms;android-28"
before_script:
  - wget http://services.gradle.org/distributions/gradle-3.5-bin.zip
  - unzip -qq gradle-3.5-bin.zip
  - export GRADLE_HOME=$PWD/gradle-3.5
  - export PATH=$GRADLE_HOME/bin:$PATH
  - git clone https://github.com/flutter/flutter.git ../flutter
  - ../flutter/bin/flutter doctor
  - chmod +x scripts/deploy_telegram.sh
script:
  - ../flutter/bin/flutter test
  - ../flutter/bin/flutter build apk
# after_script:
#  - python3 scripts/format_files.py
cache:
  directories:
    - $HOME/.pub-cache

deploy:
  - provider: script
    skip_cleanup: true
    script: scripts/deploy_telegram.sh
    on:
      branch: master
# todo push on github releases
