# from https://medium.com/flutter-io/test-flutter-apps-on-travis-3fd5142ecd8c

os:
  - linux
language: python
python:
  - "3.6"
branches:
  only:
  - master
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid

before_script:
  - git clone https://github.com/flutter/flutter.git ../flutter
  - ../flutter/bin/flutter doctor
script:
  - ../flutter/bin/flutter test
after_script:
  - python3 scripts/format_files.py
cache:
  directories:
    - $HOME/.pub-cache