name: quake
description: An earthquake news app.
version: 0.2.1+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.1.6
  http: ^0.12.0+2
  sqflite: ^0.13.0+1
  shared_preferences: ^0.4.3
  intl: ^0.15.7
  rxdart: ^0.21.0
  flare_flutter: ^1.3.12
  location: ^2.3.5
  connectivity: ^0.4.3+1
  flutter_map: ^0.5.0
  share: ^0.6.1
  timeago: ^2.0.14
  package_info: ^0.4.0+3
  liquid_pull_to_refresh: ^1.1.0
  k_means_cluster: ^0.2.2
  url_launcher: ^5.0.2
  background_fetch: ^0.1.0
  flutter_local_notifications: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
  intl_translation: ^0.17.2
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/logo_with_bg.png"

flutter:
  uses-material-design: true
  assets:
    - assets/flare/monitor.flr
    - assets/flare/earth.flr
    - assets/flare/pulse.flr
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 500
    - family: Quake
      fonts:
        - asset: assets/fonts/Quake.ttf
