name: quake
description: Material design earthquake tracker app

version: 3.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  xml2json: ^4.2.0
  moor: ^2.4.2
  moor_ffi: ^0.4.0
  path: ^1.6.4
  path_provider: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  test: ^1.14.2
  moor_generator: ^2.4.0
  build_runner: ^1.8.1

flutter:
  uses-material-design: true
